name:                wm
version:             0.1.0.1
github:              "peri4n/wm"
license:             BSD3
author:              "Fabian Bull"
maintainer:          "bull.fabian@googlemail.com"
copyright:           "2019 Author Fabian Bull"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/peri4n/wm#readme>

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.15
- xmonad-contrib >= 0.15
- xmonad-spotify
- containers
- X11

library:
  source-dirs: src

executables:
  wm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wm

tests:
  wm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wm
